### PR TITLE
Updating to latest Relaton version

### PR DESCRIPTION
**Pull request by strogonoff**
Most changes here involve supporting the latest bibliographic data model and preparing for fixing bibliographic data generatori version to avoid breaking changes in bibliographic data.

Other changes:

- Triggering reindex in management GUI will always result in an indexing run, even if data repository has not changed. (In API this is controlled via `force` flag.)
- `RELATON_VERSION.txt` was added to inform bibliographic data crawler & generation systems about supported bibliographic model schema version.
- Indexer logs in management GUI now make it easier to locate unresolved validation errors. More data validation improvements regarding the GUI are coming.
- Some improvements to documentation and development environment setup were made.

### CODE REVIEW

**Comment by stefanomunarini** [comment]
Contains fix for #307

**Comment by strogonoff** [comment]
The build is green now. The issues that caused it to fail were in fact concerning tests themselves and the fact that ietf-ribose bibxml-service fork did not have the latest changes from ietf-tools upstream.

**Comment by kesara** [comment]
> The build is green now. The issues that caused it to fail were in fact concerning tests themselves and the fact that ietf-ribose bibxml-service fork did not have the latest changes from ietf-tools upstream.
Ack!
@strogonoff, Is this PR ready now?

**Comment by stefanomunarini** [comment]
> > The build is green now. The issues that caused it to fail were in fact concerning tests themselves and the fact that ietf-ribose bibxml-service fork did not have the latest changes from ietf-tools upstream.
> 
> Ack! @strogonoff, Is this PR ready now?

Yes, @kesara ! PR is ready

**Comment by strogonoff** [comment]
@kesara Are we sure all changes were merged? The message above says you merged only one commit.

**Comment by strogonoff** [comment]
Sorry, stupid question, I see that main branch has the right code, just Github GUI being confused probably.

**Comment by kesara** [comment]
@strogonoff FYI: These changes are merged and deployed to bib.ietf.org.

**Pull request merged**
