### PR TITLE
fix(xml2rfc): don't treat subseries ID as RFC ID

### LINKED ISSUE #260: bibxml-rfcsubseries has RFC
### Describe the issue

Following URLs with RFC references should generate a `404` response because `bibxml-rfcsubseries` is for STD, BCP and FYI.

* https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.RFC.1737.xml
* https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.RFC.9000.xml

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by strogonoff**
fix #260

### CODE REVIEW

**Comment by strogonoff** [comment]
Evidently the CI error is not related to the change.

**Review by kesara — APPROVED** [review]

**Review by kesara — CHANGES_REQUESTED** [review]
Tests needs to be updated.
RFC 4037 is used in `test_rfcsubseries`

```
======================================================================
ERROR: test_rfcsubseries (xml2rfc_compat.tests.test_adapters.XML2RFCAdaptersTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/xml2rfc_compat/tests/test_adapters.py", line 124, in test_rfcsubseries
    bibitem = adapter.resolve()
  File "/code/xml2rfc_compat/adapters.py", line 86, in resolve
    refs = self.fetch_refs()
  File "/code/xml2rfc_compat/adapters.py", line 181, in fetch_refs
    if (query := self.get_docid_query()):
  File "/code/xml2rfc_compat/adapters.py", line 189, in get_docid_query
    if (docid := self.resolve_docid()):
  File "/code/bibxml/xml2rfc_adapters.py", line 556, in resolve_docid
    raise ValueError("Invalid rfcsubseries ID")
ValueError: Invalid rfcsubseries ID

======================================================================
ERROR: test_rfcsubseries_not_found (xml2rfc_compat.tests.test_adapters.XML2RFCAdaptersTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/xml2rfc_compat/tests/test_adapters.py", line 130, in test_rfcsubseries_not_found
    adapter.resolve()
  File "/code/xml2rfc_compat/adapters.py", line 86, in resolve
    refs = self.fetch_refs()
  File "/code/xml2rfc_compat/adapters.py", line 181, in fetch_refs
    if (query := self.get_docid_query()):
  File "/code/xml2rfc_compat/adapters.py", line 189, in get_docid_query
    if (docid := self.resolve_docid()):
  File "/code/bibxml/xml2rfc_adapters.py", line 556, in resolve_docid
    raise ValueError("Invalid rfcsubseries ID")
ValueError: Invalid rfcsubseries ID
```

**Comment by kesara** [comment]
> Evidently the CI error is not related to the change.

@strogonoff, We might have to update the CI tests to show the actual errors.
I ran it locally, logs were written to `./test-artifacts/stderr.log`.

See https://github.com/ietf-tools/bibxml-service/pull/291#pullrequestreview-1095783929

**Comment by strogonoff** [comment]
Looks like `rfcs_ref` should be `rfcsubseries_ref` in the test?

**Comment by strogonoff** [comment]
@kesara Let’s merge these changes now—tests are going to be updated in another PR.

**Pull request merged**
