### PR TITLE
Fix/deploy workflow

### PR DESCRIPTION
**Pull request by stefanomunarini**

### CODE REVIEW

**Comment by stefanomunarini** [comment]
Can you take a look at this @kesara ? It fixes the warnings for the main workflow (see https://github.com/ietf-tools/bibxml-service/actions/runs/6345311605 )

**Comment by kesara** [comment]
@stefanomunarini you can actually delete these two GHAs because bib.ietf.org is not hosted on AWS. I think this is deploying to https://dev.bibxml.org/ which is managed by ribose.
So, these GHAs could be part of the ribose fork of bibxml-service.

**Comment by stefanomunarini** [comment]
I see. Do you want to introduce an ietf-tools `.gitignore` for such matter?

**Comment by kesara** [comment]
> I see. Do you want to introduce an ietf-tools `.gitignore` for such matter? @kesara

Do you mean adding those two files to `.gitignore`?
Wouldn't that affect the forks as well?

**Comment by kesara** [comment]
Yeah, I think if these workflows are required by a fork, the fork should maintain those files, without pushing them to the upstream branch.
Another option is ribose can have a separate project just for the workflow.

**Pull request closed without merging**
